base_url = "https://thomaszahner.ch"
theme = "apollo"
title = "Thomas Zahner"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Enable atom feed
generate_feeds = true

taxonomies = [
  { name = "tags" },
]

[markdown.highlighting]
error_on_missing_language = true
theme = "catppuccin-macchiato"

[extra]
menu = [
    { name = "Projects", url = "/projects" },
    { name = "Posts", url = "/posts" },
    { name = "Tags", url = "/tags" },
    { name = "About", url = "/about" },
]

socials = [
  { name = "GitHub", url = "https://github.com/thomas-zahner", icon = "github" },
  { name = "GitLab", url = "https://gitlab.com/thomas-zahner", icon = "gitlab" },
  { name = "Mastodon", url = "https://mastodon.social/@thomas_zahner", icon = "mastodon" },
  { name = "Atom", url = "/atom.xml", icon = "rss" },
]
