base_url = "https://thomaszahner.ch"
theme = "terminimal"
title = "Thomas Zahner"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  {name = "tags"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "thomaszahner.ch"

menu_items = [
    {name = "Blog", url = "$BASE_URL"},
    {name = "Tags", url = "$BASE_URL/tags"},
    {name = "Projects", url = "$BASE_URL/projects"},
    {name = "About", url = "$BASE_URL/about"},
]
